# Generated by Django 3.0.6 on 2020-06-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200608_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
